import { useState } from 'react';
import { 
  Download, 
  FileText, 
  X, 
  CheckCircle,
  Loader2,
  FileJson,
  Printer
} from 'lucide-react';
import { ContractAnalysis } from '../types';

interface ExportModalProps {
  analysis: ContractAnalysis;
  onClose: () => void;
  onExport: () => void;
}

export function ExportModal({ analysis, onClose, onExport }: ExportModalProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportComplete, setExportComplete] = useState(false);

  const generatePDFContent = () => {
    const getRiskEmoji = (level: string) => {
      switch (level) {
        case 'high': return '🔴';
        case 'medium': return '🟡';
        case 'low': return '🟢';
        default: return '⚪';
      }
    };

    let content = `
CONTRACT ANALYSIS REPORT
========================

Generated by LegalLens - Contract Analysis & Risk Assessment Bot
Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

═══════════════════════════════════════════════════════════════════

DOCUMENT INFORMATION
--------------------
File Name: ${analysis.fileName}
Contract Type: ${analysis.contractType.charAt(0).toUpperCase() + analysis.contractType.slice(1)}
Language: ${analysis.language.charAt(0).toUpperCase() + analysis.language.slice(1)}
Analysis Date: ${analysis.uploadedAt.toLocaleString()}

═══════════════════════════════════════════════════════════════════

OVERALL RISK ASSESSMENT
-----------------------
Risk Score: ${analysis.overallRiskScore}/100
Risk Level: ${getRiskEmoji(analysis.overallRiskLevel)} ${analysis.overallRiskLevel.toUpperCase()}

═══════════════════════════════════════════════════════════════════

EXECUTIVE SUMMARY
-----------------
${analysis.summary}

═══════════════════════════════════════════════════════════════════

KEY FINDINGS
------------
${analysis.keyFindings.map((f, i) => `${i + 1}. ${f}`).join('\n')}

═══════════════════════════════════════════════════════════════════

RECOMMENDATIONS
---------------
${analysis.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

`;

    if (analysis.complianceIssues.length > 0) {
      content += `
═══════════════════════════════════════════════════════════════════

COMPLIANCE CONCERNS
-------------------
${analysis.complianceIssues.map((c, i) => `${i + 1}. ${c}`).join('\n')}

`;
    }

    if (analysis.ambiguities.length > 0) {
      content += `
═══════════════════════════════════════════════════════════════════

AMBIGUOUS LANGUAGE DETECTED
---------------------------
${analysis.ambiguities.map((a, i) => `${i + 1}. ${a}`).join('\n')}

`;
    }

    if (analysis.entities.length > 0) {
      content += `
═══════════════════════════════════════════════════════════════════

EXTRACTED ENTITIES
------------------
${analysis.entities.map(e => `• ${e.type.toUpperCase()}: ${e.value}`).join('\n')}

`;
    }

    content += `
═══════════════════════════════════════════════════════════════════

CLAUSE-BY-CLAUSE ANALYSIS
-------------------------

`;

    analysis.clauses.forEach((clause, index) => {
      content += `
CLAUSE ${index + 1}: ${clause.title}
${'-'.repeat(50)}
Type: ${clause.type}
Risk Score: ${clause.riskScore}/100 ${getRiskEmoji(clause.riskLevel)}
Category: ${clause.category}
${clause.isUnfavorable ? '⚠️ MARKED AS UNFAVORABLE' : ''}

Plain Language Explanation:
${clause.explanation}

`;

      if (clause.concerns.length > 0) {
        content += `Concerns:
${clause.concerns.map(c => `  • ${c}`).join('\n')}

`;
      }

      if (clause.suggestions.length > 0) {
        content += `Negotiation Suggestions:
${clause.suggestions.map(s => `  → ${s}`).join('\n')}

`;
      }

      content += '\n';
    });

    content += `
═══════════════════════════════════════════════════════════════════

DISCLAIMER
----------
This analysis is provided for informational purposes only and does 
not constitute legal advice. The analysis is based on automated 
processing and may not capture all nuances of the contract. 

Always consult with a qualified legal professional before making 
any decisions based on this report.

═══════════════════════════════════════════════════════════════════

Report generated by LegalLens
© ${new Date().getFullYear()} Contract Analysis & Risk Assessment Bot
For Indian SMEs
`;

    return content;
  };

  const handleExportTXT = () => {
    setIsExporting(true);
    
    setTimeout(() => {
      const content = generatePDFContent();
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `contract-analysis-${analysis.id}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      setIsExporting(false);
      setExportComplete(true);
      onExport();
      
      setTimeout(() => {
        setExportComplete(false);
      }, 2000);
    }, 1000);
  };

  const handleExportJSON = () => {
    setIsExporting(true);
    
    setTimeout(() => {
      const exportData = {
        ...analysis,
        exportedAt: new Date().toISOString(),
        version: '1.0'
      };
      
      const content = JSON.stringify(exportData, null, 2);
      const blob = new Blob([content], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `contract-analysis-${analysis.id}.json`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      setIsExporting(false);
      setExportComplete(true);
      onExport();
      
      setTimeout(() => {
        setExportComplete(false);
      }, 2000);
    }, 1000);
  };

  const handlePrint = () => {
    const content = generatePDFContent();
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Contract Analysis Report</title>
            <style>
              body { font-family: 'Courier New', monospace; padding: 40px; line-height: 1.6; }
              pre { white-space: pre-wrap; word-wrap: break-word; }
            </style>
          </head>
          <body>
            <pre>${content}</pre>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-lg w-full overflow-hidden">
        <div className="p-6 border-b border-slate-200 flex items-center justify-between">
          <h3 className="text-xl font-semibold text-slate-800">Export Analysis Report</h3>
          <button
            onClick={onClose}
            className="p-2 hover:bg-slate-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-slate-500" />
          </button>
        </div>
        
        <div className="p-6 space-y-4">
          <p className="text-slate-600">
            Choose an export format for your contract analysis report:
          </p>
          
          <div className="space-y-3">
            {/* TXT Export */}
            <button
              onClick={handleExportTXT}
              disabled={isExporting}
              className="w-full p-4 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-xl flex items-center gap-4 transition-colors disabled:opacity-50"
            >
              <div className="p-3 bg-blue-100 rounded-lg">
                <FileText className="w-6 h-6 text-blue-600" />
              </div>
              <div className="flex-1 text-left">
                <p className="font-medium text-slate-800">Text Report (.txt)</p>
                <p className="text-sm text-slate-500">Formatted plain text for easy reading</p>
              </div>
              {isExporting ? (
                <Loader2 className="w-5 h-5 text-slate-400 animate-spin" />
              ) : exportComplete ? (
                <CheckCircle className="w-5 h-5 text-emerald-500" />
              ) : (
                <Download className="w-5 h-5 text-slate-400" />
              )}
            </button>

            {/* JSON Export */}
            <button
              onClick={handleExportJSON}
              disabled={isExporting}
              className="w-full p-4 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-xl flex items-center gap-4 transition-colors disabled:opacity-50"
            >
              <div className="p-3 bg-amber-100 rounded-lg">
                <FileJson className="w-6 h-6 text-amber-600" />
              </div>
              <div className="flex-1 text-left">
                <p className="font-medium text-slate-800">JSON Data (.json)</p>
                <p className="text-sm text-slate-500">Structured data for further processing</p>
              </div>
              {isExporting ? (
                <Loader2 className="w-5 h-5 text-slate-400 animate-spin" />
              ) : (
                <Download className="w-5 h-5 text-slate-400" />
              )}
            </button>

            {/* Print */}
            <button
              onClick={handlePrint}
              disabled={isExporting}
              className="w-full p-4 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-xl flex items-center gap-4 transition-colors disabled:opacity-50"
            >
              <div className="p-3 bg-emerald-100 rounded-lg">
                <Printer className="w-6 h-6 text-emerald-600" />
              </div>
              <div className="flex-1 text-left">
                <p className="font-medium text-slate-800">Print Report</p>
                <p className="text-sm text-slate-500">Open print dialog for PDF or paper</p>
              </div>
              <Printer className="w-5 h-5 text-slate-400" />
            </button>
          </div>
        </div>
        
        <div className="p-6 border-t border-slate-200 bg-slate-50">
          <p className="text-xs text-slate-500 text-center">
            Reports include all analysis data including risk scores, clause breakdowns, and recommendations.
          </p>
        </div>
      </div>
    </div>
  );
}
